### ISSUE TITLE
Task was destroyed but it is pending

### ISSUE THREAD

**Issue by howgermcgredy** [HoloArchivists/fc2-live-dl#42] opened 2023-06-16 12:49 UTC
![image](https://github.com/HoloArchivists/fc2-live-dl/assets/116721444/f8b3352b-2950-4ecd-b0f9-6f63abe557b3)
I have this loop error. I didn't see any similar question on google, so I can't solve this question.
I didn't saw this error six days ago, it appear first time today.
Waiting for the help, thanks a lot.

**Comment by hizkifw** [comment] 2023-06-16 12:54
Hello, can I get some details?
- Which version of Python are you running? (`python --version`)
- Which version of fc2-live-dl are you using?
- What command did you use to run fc2-live-dl?

**Comment by howgermcgredy** [comment] 2023-06-16 13:12
Python version is 3.10.8
![image](https://github.com/HoloArchivists/fc2-live-dl/assets/116721444/43194c27-9a25-47dc-8c55-9ecef63dfdbb)
This is the command that I run fc2-live-dl.
But I don't know how to check my fc2-live-dl.

**Comment by hizkifw** [comment] 2023-06-22 15:14
Can you check with `fc2-live-dl --version`

Try updating to the latest version with `pip install --upgrade fc2-live-dl`

**Comment by howgermcgredy** [comment] 2023-06-25 19:20
> Can you check with `fc2-live-dl --version`
> 
> Try updating to the latest version with `pip install --upgrade fc2-live-dl`

Understand, I will try it later.
Thank's for help!!!

**Comment by howgermcgredy** [comment] 2023-06-25 19:27
![image](https://github.com/HoloArchivists/fc2-live-dl/assets/116721444/dff96df9-e67d-49a1-b36f-512ec05cf564)
I have a new question after upgrade it...
The code is same since last version.

**Comment by hizkifw** [comment] 2023-07-06 05:00
I'm closing this issue now, feel free to reopen if the issue is still happening

**Closed by hizkifw** 2023-07-06 05:00 UTC
